#
# Makefile for the linux system information tables.
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definition is now in the main makefile...

O_TARGET := table.o
OX_OBJS  := main.o

M_TARGET := table_mod.o
MX_OBJS  := module.o

include $(TOPDIR)/Rules.make
