stages:
  - build

variables:
  FEDORA_DEPENDENCIES:
    gawk
    gettext-devel
    glib2-devel
    gobject-introspection-devel
    gtk-doc
    perl
    texinfo
    texinfo-tex

build-fedora:
  image: fedora:latest
  stage: build
  except:
    - tags
  before_script:
    - dnf update -y --nogpgcheck
    - dnf -y install --nogpgcheck $FEDORA_DEPENDENCIES
  script:
    - mkdir _build
    - cd _build
    - ../autogen.sh --disable-dependency-tracking
    - make
    - make install
    - make distcheck
