stages:
  - build

variables:
  FEDORA_DEPENDENCIES:
    gawk
    gettext-devel
    glib2-devel
    gobject-introspection-devel
    gtk-doc
    perl
    texinfo
    texinfo-tex
  FEDORA_DEPENDENCIES_ABI_CHECK:
    libabigail
    intltool
  LAST_ABI_BREAK: "abccaf488a929de1e95e6a748485575dec52c998"

build-fedora:
  image: fedora:latest
  stage: build
  except:
    - tags
  before_script:
    - dnf update -y --nogpgcheck
    - dnf -y install --nogpgcheck $FEDORA_DEPENDENCIES
  script:
    - mkdir _build
    - cd _build
    - ../autogen.sh --disable-dependency-tracking
    - make
    - make install
    - make distcheck
    - cd ..
    - curl https://gitlab.freedesktop.org/hadess/check-abi/-/raw/main/contrib/check-abi-fedora.sh | bash
    - dnf install -y $FEDORA_DEPENDENCIES_ABI_CHECK
    - check-abi ${LAST_ABI_BREAK} $(git rev-parse HEAD)
