stages:
  - build
  - deploy
  - package
  - test

build-fedora:
  image: fedora:latest
  stage: build
  except:
    - tags
  before_script:
    - dnf update -y --nogpgcheck
    - dnf -y install --nogpgcheck
      gawk gettext-devel glib2-devel gobject-introspection-devel gtk-doc perl
      texinfo texinfo-tex
  script:
    - ./autogen.sh --disable-dependency-tracking
    - make

deploy-install:
    stage: deploy
    extends: build-fedora
    script:
      - ./autogen.sh --disable-dependency-tracking
      - make install

package-distcheck:
    stage: package
    extends: build-fedora
    script:
      - ./autogen.sh --disable-dependency-tracking
      - make distcheck


test-examples:
    stage: test
    extends: build-fedora
    script:
      - ./examples/affinity
      - ./examples/df
      - ./examples/diskio
      - ./examples/first
      - ./examples/free
      - ./examples/mountlist
      - ./examples/netlist
      - ./examples/netload
      - ./examples/openfiles
      - ./examples/pprint
      - ./examples/procargs
      - ./examples/proclist
      - ./examples/procmap
      - ./examples/second
      - ./examples/smp
      - ./examples/sysdeps
      - ./examples/timings
      - ./examples/wd

