stages:
  - build
  - abi

variables:
  FEDORA_DEPENDENCIES:
    gawk
    gettext-devel
    glib2-devel
    gobject-introspection-devel
    gtk-doc
    perl
    texinfo
    texinfo-tex
  FEDORA_DEPENDENCIES_ABI_CHECK:
    libabigail
    intltool
  LAST_ABI_BREAK: "abccaf488a929de1e95e6a748485575dec52c998"
  UBUNTU_DEPENDENCIES:
    autoconf
    automake
    autopoint
    gettext
    glib2.0
    gtk-doc-tools
    libgirepository1.0-dev
    libtool
    make
    texinfo
    texlive

build-fedora:
  image: fedora:latest
  stage: build
  except:
    - tags
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $FEDORA_DEPENDENCIES
  script:
    - mkdir _build
    - cd _build
    - ../autogen.sh --disable-dependency-tracking
    - make
    - make install
    - make distcheck

abi-fedora:
  image: fedora:latest
  stage: abi
  needs:
    - build-fedora
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $FEDORA_DEPENDENCIES $FEDORA_DEPENDENCIES_ABI_CHECK
  script:
    - curl https://gitlab.freedesktop.org/hadess/check-abi/-/raw/main/contrib/check-abi-fedora.sh | bash
    - check-abi ${LAST_ABI_BREAK} $(git rev-parse HEAD)

build-ubuntu:
  image: ubuntu:latest
  stage: build
  except:
    - tags
  before_script:
    - apt-get update
    - apt-get install -y $UBUNTU_DEPENDENCIES
  script:
    - mkdir _build
    - cd _build
    - ../autogen.sh
    - make
    - make install
    - make distcheck
