\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename libgtop.info
@settitle LibGTop Reference Manual
@setchapternewpage odd
@c %**end of header

@node Top, About, (dir), (dir)

@menu
* About::                       About LibGTop
* Reference Manual::            LibGTop Reference Manual










 --- The Detailed Node Listing ---

About LibGTop

* Availability::                Where to get LibGTop
* Supported Platforms::         Supported Platforms
* Mailing List::                Helping with LibGTop development
* Thanks::                      People who contributed to LibGTop

LibGTop Reference Manual

* glibtop_cpu::                 CPU Usage.
* glibtop_mem::                 Memory Usage.
* glibtop_swap::                Swap Usage.
* glibtop_uptime::              System Uptime.
* glibtop_loadavg::             Load Average.
@end menu

@include about.texi
@include reference.texi

@bye

