@node Top, About, (dir), (dir)

@menu
* About::                       About LibGTop
* White Paper::                 LibGTop White Paper
* Reference Manual::            LibGTop Reference Manual







 --- The Detailed Node Listing ---

About LibGTop

* Availability::                Where to get LibGTop
* Supported Platforms::         Supported Platforms
* Mailing List::                Helping with LibGTop development
* Thanks::                      People who contributed to LibGTop

LibGTop White Paper

* Introduction::                

LibGTop Reference Manual

* glibtop_cpu::                 CPU Usage.
* glibtop_mem::                 Memory Usage.
* glibtop_swap::                Swap Usage.
* glibtop_uptime::              System Uptime.
* glibtop_loadavg::             Load Average.
* glibtop_proclist::            Process List.
* glibtop_proc_state::          Process State.
* glibtop_proc_uid::            Process UID and TTY Information.
* glibtop_proc_mem::            Process Memory Information.
* glibtop_proc_time::           Process Time Information.
* glibtop_proc_signal::         Process Signal Information.
* glibtop_proc_kernel::         Process Kernel Data Information.
* glibtop_proc_segment::        Process Segment Information.
* glibtop_proc_args::           Process Arguments.
* glibtop_proc_map::            Process Memory Maps.
* glibtop_netload::             Network Load.
* glibtop_ppp::                 PPP Usage.
* glibtop_mountlist::           Mount List.
* glibtop_fsusage::             File System Usage.
@end menu

@include about.texi
@include white-paper.texi
@include reference.texi

